export interface Word {
  word: string;
  hint: string;
}

const easy: Word[] = [
  { word: 'calm', hint: 'Peaceful and still' },
  { word: 'leaf', hint: 'Grows on a tree' },
  { word: 'rain', hint: 'Falls from the sky' },
  { word: 'pond', hint: 'Small body of water' },
  { word: 'bird', hint: 'Creature with wings' },
  { word: 'seed', hint: 'Start of a plant' },
  { word: 'moon', hint: 'Lights up the night' },
  { word: 'wind', hint: 'Moving air' },
  { word: 'frog', hint: 'Hops on lily pads' },
  { word: 'nest', hint: 'A bird\'s home' },
  { word: 'dawn', hint: 'Start of the day' },
  { word: 'dusk', hint: 'End of the day' },
  { word: 'mist', hint: 'Thin fog' },
  { word: 'pine', hint: 'Evergreen tree' },
  { word: 'vine', hint: 'Climbing plant' },
  { word: 'root', hint: 'Underground part of a plant' },
  { word: 'fern', hint: 'Leafy forest plant' },
  { word: 'hike', hint: 'Walk in nature' },
  { word: 'dew', hint: 'Morning moisture' },
  { word: 'moss', hint: 'Soft green ground cover' },
  { word: 'haze', hint: 'Slight fog in the air' },
  { word: 'glow', hint: 'Soft light' },
  { word: 'wave', hint: 'Ocean movement' },
  { word: 'path', hint: 'Trail through the woods' },
  { word: 'bloom', hint: 'Flower opening' },
  { word: 'stone', hint: 'Small rock' },
  { word: 'creek', hint: 'Small stream' },
  { word: 'shade', hint: 'Cool area under a tree' },
  { word: 'petal', hint: 'Part of a flower' },
  { word: 'drift', hint: 'Float gently' },
  { word: 'cloud', hint: 'White and fluffy in the sky' },
  { word: 'trail', hint: 'Forest walkway' },
  { word: 'grove', hint: 'Small group of trees' },
  { word: 'shore', hint: 'Edge of the water' },
  { word: 'light', hint: 'Opposite of dark' },
  { word: 'earth', hint: 'Soil beneath your feet' },
  { word: 'ocean', hint: 'Vast body of water' },
  { word: 'daisy', hint: 'Simple white flower' },
  { word: 'willow', hint: 'Weeping tree' },
  { word: 'brook', hint: 'Babbling water' },
];

const medium: Word[] = [
  { word: 'garden', hint: 'Where flowers grow' },
  { word: 'breeze', hint: 'Gentle wind' },
  { word: 'forest', hint: 'Dense collection of trees' },
  { word: 'meadow', hint: 'Open grassy field' },
  { word: 'canopy', hint: 'Treetop cover' },
  { word: 'pebble', hint: 'Smooth small stone' },
  { word: 'stream', hint: 'Flowing water' },
  { word: 'sunset', hint: 'Evening sky colors' },
  { word: 'bamboo', hint: 'Tall fast-growing grass' },
  { word: 'bonsai', hint: 'Miniature tree art' },
  { word: 'cherry', hint: 'Blossom tree fruit' },
  { word: 'clover', hint: 'Lucky if it has four leaves' },
  { word: 'gentle', hint: 'Soft and kind' },
  { word: 'harbor', hint: 'Sheltered port' },
  { word: 'island', hint: 'Land surrounded by water' },
  { word: 'jasmine', hint: 'Fragrant white flower' },
  { word: 'lantern', hint: 'Portable light' },
  { word: 'nectar', hint: 'Sweet flower liquid' },
  { word: 'orchid', hint: 'Elegant exotic flower' },
  { word: 'quartz', hint: 'Common crystal' },
  { word: 'ripple', hint: 'Small wave on water' },
  { word: 'serene', hint: 'Calm and peaceful' },
  { word: 'thrive', hint: 'Grow vigorously' },
  { word: 'valley', hint: 'Low area between hills' },
  { word: 'zenith', hint: 'Highest point' },
  { word: 'aurora', hint: 'Northern lights' },
  { word: 'branch', hint: 'Arm of a tree' },
  { word: 'canyon', hint: 'Deep narrow valley' },
  { word: 'fossil', hint: 'Ancient remains in stone' },
  { word: 'glacier', hint: 'Slow-moving ice mass' },
  { word: 'turtle', hint: 'Slow shelled creature' },
  { word: 'rabbit', hint: 'Hops through meadows' },
  { word: 'summer', hint: 'Warmest season' },
  { word: 'autumn', hint: 'Leaves change color' },
  { word: 'spring', hint: 'Season of new growth' },
  { word: 'temple', hint: 'Place of meditation' },
  { word: 'bridge', hint: 'Crosses over water' },
  { word: 'candle', hint: 'Wax light source' },
  { word: 'feather', hint: 'Light as a...' },
  { word: 'hollow', hint: 'Empty inside' },
];

const hard: Word[] = [
  { word: 'tranquil', hint: 'Extremely peaceful' },
  { word: 'blossom', hint: 'Flower in full bloom' },
  { word: 'whisper', hint: 'Speak very softly' },
  { word: 'crystal', hint: 'Clear mineral formation' },
  { word: 'harmony', hint: 'Perfect balance' },
  { word: 'horizon', hint: 'Where earth meets sky' },
  { word: 'morning', hint: 'Early part of the day' },
  { word: 'thunder', hint: 'Sound after lightning' },
  { word: 'shimmer', hint: 'Soft sparkling light' },
  { word: 'flutter', hint: 'Light rapid movement' },
  { word: 'firefly', hint: 'Glowing night insect' },
  { word: 'cascade', hint: 'Small waterfall' },
  { word: 'drought', hint: 'Long period without rain' },
  { word: 'essence', hint: 'Core nature of something' },
  { word: 'fragrant', hint: 'Having a pleasant smell' },
  { word: 'lavender', hint: 'Purple calming herb' },
  { word: 'majestic', hint: 'Grand and impressive' },
  { word: 'nostalgic', hint: 'Longing for the past' },
  { word: 'paradise', hint: 'Perfect peaceful place' },
  { word: 'radiance', hint: 'Bright glowing light' },
  { word: 'sapphire', hint: 'Blue precious stone' },
  { word: 'twilight', hint: 'Light between day and night' },
  { word: 'umbrella', hint: 'Rain protection' },
  { word: 'verdant', hint: 'Lush and green' },
  { word: 'wildfire', hint: 'Uncontrolled forest blaze' },
  { word: 'solitude', hint: 'Being peacefully alone' },
  { word: 'rainfall', hint: 'Water from clouds' },
  { word: 'mountain', hint: 'Tall earth formation' },
  { word: 'serenity', hint: 'State of calm' },
  { word: 'starlight', hint: 'Glow from the night sky' },
  { word: 'botanical', hint: 'Related to plants' },
  { word: 'evergreen', hint: 'Always has leaves' },
  { word: 'moonlight', hint: 'Nighttime illumination' },
  { word: 'waterfall', hint: 'Water falling from a cliff' },
  { word: 'butterfly', hint: 'Colorful winged insect' },
  { word: 'dandelion', hint: 'Fluffy wish flower' },
  { word: 'dragonfly', hint: 'Hovering pond insect' },
  { word: 'sanctuary', hint: 'Safe peaceful place' },
  { word: 'wisteria', hint: 'Cascading purple vine' },
  { word: 'enchanted', hint: 'Under a magical spell' },
];

export type Difficulty = 'easy' | 'medium' | 'hard';

export const wordsByDifficulty: Record<Difficulty, Word[]> = {
  easy,
  medium,
  hard,
};
