export interface Word {
  word: string;
  hint: string;
  points: number;
}

const words: Word[] = [
  // 4-letter (100 pts)
  { word: 'calm', hint: 'Peaceful and still', points: 100 },
  { word: 'leaf', hint: 'Grows on a tree', points: 100 },
  { word: 'rain', hint: 'Falls from the sky', points: 100 },
  { word: 'pond', hint: 'Small body of water', points: 100 },
  { word: 'bird', hint: 'Creature with wings', points: 100 },
  { word: 'seed', hint: 'Start of a plant', points: 100 },
  { word: 'moon', hint: 'Lights up the night', points: 100 },
  { word: 'wind', hint: 'Moving air', points: 100 },
  { word: 'frog', hint: 'Hops on lily pads', points: 100 },
  { word: 'nest', hint: 'A bird\'s home', points: 100 },
  { word: 'dawn', hint: 'Start of the day', points: 100 },
  { word: 'dusk', hint: 'End of the day', points: 100 },
  { word: 'mist', hint: 'Thin fog', points: 100 },
  { word: 'pine', hint: 'Evergreen tree', points: 100 },
  { word: 'vine', hint: 'Climbing plant', points: 100 },
  { word: 'root', hint: 'Underground part of a plant', points: 100 },
  { word: 'fern', hint: 'Leafy forest plant', points: 100 },
  { word: 'hike', hint: 'Walk in nature', points: 100 },
  { word: 'moss', hint: 'Soft green ground cover', points: 100 },
  { word: 'haze', hint: 'Slight fog in the air', points: 100 },
  { word: 'glow', hint: 'Soft light', points: 100 },
  { word: 'wave', hint: 'Ocean movement', points: 100 },
  { word: 'path', hint: 'Trail through the woods', points: 100 },
  { word: 'tide', hint: 'Ocean rise and fall', points: 100 },
  { word: 'bark', hint: 'Tree covering', points: 100 },
  { word: 'cave', hint: 'Hollow in a rock', points: 100 },
  { word: 'dome', hint: 'Rounded roof shape', points: 100 },
  { word: 'echo', hint: 'Repeated sound', points: 100 },
  { word: 'folk', hint: 'People in general', points: 100 },
  { word: 'gust', hint: 'Sudden burst of wind', points: 100 },
  { word: 'knot', hint: 'Tied rope', points: 100 },
  { word: 'loom', hint: 'Weaving device', points: 100 },
  { word: 'myth', hint: 'Ancient story', points: 100 },
  { word: 'opal', hint: 'Iridescent gemstone', points: 100 },
  { word: 'plum', hint: 'Purple fruit', points: 100 },
  { word: 'sage', hint: 'Wise herb', points: 100 },
  { word: 'turf', hint: 'Grass-covered earth', points: 100 },
  { word: 'veil', hint: 'Thin covering', points: 100 },
  { word: 'wren', hint: 'Tiny songbird', points: 100 },
  { word: 'yarn', hint: 'Thread for knitting', points: 100 },

  // 5-letter (150 pts)
  { word: 'bloom', hint: 'Flower opening', points: 150 },
  { word: 'stone', hint: 'Small rock', points: 150 },
  { word: 'creek', hint: 'Small stream', points: 150 },
  { word: 'shade', hint: 'Cool area under a tree', points: 150 },
  { word: 'petal', hint: 'Part of a flower', points: 150 },
  { word: 'drift', hint: 'Float gently', points: 150 },
  { word: 'cloud', hint: 'White and fluffy in the sky', points: 150 },
  { word: 'trail', hint: 'Forest walkway', points: 150 },
  { word: 'grove', hint: 'Small group of trees', points: 150 },
  { word: 'shore', hint: 'Edge of the water', points: 150 },
  { word: 'light', hint: 'Opposite of dark', points: 150 },
  { word: 'earth', hint: 'Soil beneath your feet', points: 150 },
  { word: 'ocean', hint: 'Vast body of water', points: 150 },
  { word: 'daisy', hint: 'Simple white flower', points: 150 },
  { word: 'brook', hint: 'Babbling water', points: 150 },
  { word: 'amber', hint: 'Warm golden color', points: 150 },
  { word: 'bliss', hint: 'Perfect happiness', points: 150 },
  { word: 'charm', hint: 'Attractive quality', points: 150 },
  { word: 'delta', hint: 'River mouth formation', points: 150 },
  { word: 'ember', hint: 'Glowing coal', points: 150 },
  { word: 'flora', hint: 'Plant life', points: 150 },
  { word: 'grain', hint: 'Cereal seed', points: 150 },
  { word: 'haven', hint: 'Safe place', points: 150 },
  { word: 'ivory', hint: 'Creamy white', points: 150 },
  { word: 'jewel', hint: 'Precious stone', points: 150 },
  { word: 'knoll', hint: 'Small rounded hill', points: 150 },
  { word: 'lilac', hint: 'Purple flowering shrub', points: 150 },
  { word: 'manor', hint: 'Large country house', points: 150 },
  { word: 'oasis', hint: 'Desert water spot', points: 150 },
  { word: 'quill', hint: 'Feather pen', points: 150 },
  { word: 'reign', hint: 'Rule as monarch', points: 150 },
  { word: 'swift', hint: 'Moving very fast', points: 150 },
  { word: 'thorn', hint: 'Sharp plant spine', points: 150 },
  { word: 'unity', hint: 'Being one', points: 150 },
  { word: 'vigor', hint: 'Physical strength', points: 150 },
  { word: 'wheat', hint: 'Golden grain crop', points: 150 },

  // 6-letter (200 pts)
  { word: 'garden', hint: 'Where flowers grow', points: 200 },
  { word: 'breeze', hint: 'Gentle wind', points: 200 },
  { word: 'forest', hint: 'Dense collection of trees', points: 200 },
  { word: 'meadow', hint: 'Open grassy field', points: 200 },
  { word: 'canopy', hint: 'Treetop cover', points: 200 },
  { word: 'pebble', hint: 'Smooth small stone', points: 200 },
  { word: 'stream', hint: 'Flowing water', points: 200 },
  { word: 'sunset', hint: 'Evening sky colors', points: 200 },
  { word: 'bamboo', hint: 'Tall fast-growing grass', points: 200 },
  { word: 'bonsai', hint: 'Miniature tree art', points: 200 },
  { word: 'cherry', hint: 'Blossom tree fruit', points: 200 },
  { word: 'clover', hint: 'Lucky if it has four leaves', points: 200 },
  { word: 'gentle', hint: 'Soft and kind', points: 200 },
  { word: 'harbor', hint: 'Sheltered port', points: 200 },
  { word: 'island', hint: 'Land surrounded by water', points: 200 },
  { word: 'nectar', hint: 'Sweet flower liquid', points: 200 },
  { word: 'orchid', hint: 'Elegant exotic flower', points: 200 },
  { word: 'quartz', hint: 'Common crystal', points: 200 },
  { word: 'ripple', hint: 'Small wave on water', points: 200 },
  { word: 'serene', hint: 'Calm and peaceful', points: 200 },
  { word: 'thrive', hint: 'Grow vigorously', points: 200 },
  { word: 'valley', hint: 'Low area between hills', points: 200 },
  { word: 'zenith', hint: 'Highest point', points: 200 },
  { word: 'aurora', hint: 'Northern lights', points: 200 },
  { word: 'branch', hint: 'Arm of a tree', points: 200 },
  { word: 'canyon', hint: 'Deep narrow valley', points: 200 },
  { word: 'fossil', hint: 'Ancient remains in stone', points: 200 },
  { word: 'turtle', hint: 'Slow shelled creature', points: 200 },
  { word: 'rabbit', hint: 'Hops through meadows', points: 200 },
  { word: 'summer', hint: 'Warmest season', points: 200 },
  { word: 'autumn', hint: 'Leaves change color', points: 200 },
  { word: 'spring', hint: 'Season of new growth', points: 200 },
  { word: 'temple', hint: 'Place of meditation', points: 200 },
  { word: 'bridge', hint: 'Crosses over water', points: 200 },
  { word: 'candle', hint: 'Wax light source', points: 200 },
  { word: 'hollow', hint: 'Empty inside', points: 200 },
  { word: 'voyage', hint: 'Long journey', points: 200 },
  { word: 'wreath', hint: 'Circular decoration', points: 200 },
  { word: 'zephyr', hint: 'Soft gentle breeze', points: 200 },

  // 7-letter (300 pts)
  { word: 'jasmine', hint: 'Fragrant white flower', points: 300 },
  { word: 'lantern', hint: 'Portable light', points: 300 },
  { word: 'glacier', hint: 'Slow-moving ice mass', points: 300 },
  { word: 'feather', hint: 'Light as a...', points: 300 },
  { word: 'blossom', hint: 'Flower in full bloom', points: 300 },
  { word: 'whisper', hint: 'Speak very softly', points: 300 },
  { word: 'crystal', hint: 'Clear mineral formation', points: 300 },
  { word: 'harmony', hint: 'Perfect balance', points: 300 },
  { word: 'horizon', hint: 'Where earth meets sky', points: 300 },
  { word: 'morning', hint: 'Early part of the day', points: 300 },
  { word: 'thunder', hint: 'Sound after lightning', points: 300 },
  { word: 'shimmer', hint: 'Soft sparkling light', points: 300 },
  { word: 'flutter', hint: 'Light rapid movement', points: 300 },
  { word: 'firefly', hint: 'Glowing night insect', points: 300 },
  { word: 'cascade', hint: 'Small waterfall', points: 300 },
  { word: 'drought', hint: 'Long period without rain', points: 300 },
  { word: 'essence', hint: 'Core nature of something', points: 300 },
  { word: 'verdant', hint: 'Lush and green', points: 300 },
  { word: 'tranquil', hint: 'Extremely peaceful', points: 300 },
  { word: 'solstice', hint: 'Longest or shortest day', points: 300 },
  { word: 'alchemy', hint: 'Medieval chemistry', points: 300 },
  { word: 'balcony', hint: 'Elevated outdoor platform', points: 300 },
  { word: 'chimney', hint: 'Smoke exit on a roof', points: 300 },
  { word: 'daffodil', hint: 'Yellow spring flower', points: 300 },
  { word: 'freckle', hint: 'Small skin spot', points: 300 },
  { word: 'hammock', hint: 'Hanging rest net', points: 300 },
  { word: 'juniper', hint: 'Berry-bearing shrub', points: 300 },
  { word: 'kestrel', hint: 'Small hovering falcon', points: 300 },
  { word: 'nucleus', hint: 'Center of a cell', points: 300 },
  { word: 'pilgrim', hint: 'Religious traveler', points: 300 },

  // 8+ letter (400 pts)
  { word: 'fragrant', hint: 'Having a pleasant smell', points: 400 },
  { word: 'lavender', hint: 'Purple calming herb', points: 400 },
  { word: 'majestic', hint: 'Grand and impressive', points: 400 },
  { word: 'paradise', hint: 'Perfect peaceful place', points: 400 },
  { word: 'radiance', hint: 'Bright glowing light', points: 400 },
  { word: 'sapphire', hint: 'Blue precious stone', points: 400 },
  { word: 'twilight', hint: 'Light between day and night', points: 400 },
  { word: 'umbrella', hint: 'Rain protection', points: 400 },
  { word: 'wildfire', hint: 'Uncontrolled forest blaze', points: 400 },
  { word: 'solitude', hint: 'Being peacefully alone', points: 400 },
  { word: 'rainfall', hint: 'Water from clouds', points: 400 },
  { word: 'mountain', hint: 'Tall earth formation', points: 400 },
  { word: 'serenity', hint: 'State of calm', points: 400 },
  { word: 'starlight', hint: 'Glow from the night sky', points: 400 },
  { word: 'botanical', hint: 'Related to plants', points: 400 },
  { word: 'evergreen', hint: 'Always has leaves', points: 400 },
  { word: 'moonlight', hint: 'Nighttime illumination', points: 400 },
  { word: 'waterfall', hint: 'Water falling from a cliff', points: 400 },
  { word: 'butterfly', hint: 'Colorful winged insect', points: 400 },
  { word: 'dandelion', hint: 'Fluffy wish flower', points: 400 },
  { word: 'dragonfly', hint: 'Hovering pond insect', points: 400 },
  { word: 'sanctuary', hint: 'Safe peaceful place', points: 400 },
  { word: 'wisteria', hint: 'Cascading purple vine', points: 400 },
  { word: 'enchanted', hint: 'Under a magical spell', points: 400 },
  { word: 'labyrinth', hint: 'Complex maze', points: 400 },
  { word: 'nostalgic', hint: 'Longing for the past', points: 400 },
  { word: 'obsidian', hint: 'Volcanic black glass', points: 400 },
  { word: 'porcelain', hint: 'Fine ceramic material', points: 400 },
  { word: 'quicksand', hint: 'Sinking wet sand', points: 400 },
  { word: 'reservoir', hint: 'Water storage lake', points: 400 },
];

export const allWords = words;

export type TimeMode = 60 | 90 | 120;

export const TIME_LABELS: Record<TimeMode, string> = {
  60: '1 min',
  90: '1:30',
  120: '2 min',
};
